version: '3'

services:

  mysql:
    image: mysql:8 # 使用的镜像
    container_name: lodi_mysql # 启动的实例名称
    environment:
      MYSQL_ROOT_PASSWORD:  # root 用户密码
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - /root/lodi/mysql:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
    restart: always # 崩溃后自动重启
    networks:
      - lodi-net # 指定网络

  redis:
    image: redis:6.2.0
    container_name: lodi_redis # 启动的实例名称
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD:
    volumes:
      - /root/lodi/redis:/data
      - /root/lodi/redis/redis.conf:/etc/redis/redis.conf
    networks:
      - lodi-net # 指定网络

  nacos:
    image: nacos/nacos-server:v2.2.3-slim
    container_name: lodi_nacos # 启动的实例名称
    ports:
      - "8848:8848"
    networks:
      - lodi-net # 指定网络
    volumes:
      - /root/lodi/nacos/logs:/home/nacos/logs
      - /root/lodi/nacos/conf:/home/nacos/conf
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
      - JVM_XMS=128m  # 堆内存最小值
      - JVM_XMX=256m  # 堆内存最大值
      # 使用 mysql 作为数据库
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=lodi_mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=
      # 设置连接 mysql 的连接参数
      - MYSQL_DB_PARAM="characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai"

networks:
  lodi-net: